name: face_liveness_detection_randomized_plugin
description: "A Flutter plugin for liveness detection with randomized challenge response method"
version: 1.2.1
repository: "https://github.com/UgahJoy/face_liveness_dectector.git"

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_face_detection: ^0.13.1
  easy_debounce: ^2.0.3
  camera: ^0.11.2
  equatable: ^2.0.5
  image: ^4.5.4
  lottie: ^3.3.1
  collection: ^1.18.0
  screen_brightness: ^2.1.2

dependency_overrides:
  camera_android_camerax: 0.6.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: 


  assets:
    - packages/face_liveness_detection_randomized_plugin/src/core/assets/face-id-anim.json
    - packages/face_liveness_detection_randomized_plugin/src/core/assets/face-detected.json